// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resort.Infrastructure.Data;

#nullable disable

namespace Resort.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250203173324_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resort.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 0,
                            CreatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1695),
                            Description = "This is details of Villa 1",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.independent.co.uk%2Ftravel%2Fvilla-holidays-europe-spain-greece-portugal-cyprus-b2472690.html&psig=AOvVaw25JOKvkOKym5g2kAZYqZ9O&ust=1737838204750000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOCdp_mdj4sDFQAAAAAdAAAAABAE",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 300,
                            UpdatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1761)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 0,
                            CreatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1766),
                            Description = "This is details of Villa 2",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.villaplus.com%2Fbest-villa-holidays&psig=AOvVaw25JOKvkOKym5g2kAZYqZ9O&ust=1737838204750000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCOCdp_mdj4sDFQAAAAAdAAAAABAJ",
                            Name = "Palace Villa",
                            Occupancy = 4,
                            Price = 150.0,
                            Sqft = 200,
                            UpdatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1769)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 0,
                            CreatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1776),
                            Description = "This is details of Villa 3",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.rentvillasalgarve.co.uk%2Fmedia%2F2418546%2FLuxury-holiday-villa-rental-Quinta-do-Lago.jpg%3Fwidth%3D600%26height%3D420%26scale%3Dboth%26mode%3Dcrop%26quality%3D75&tbnid=2pgayn9pyvB0yM&vet=10CBIQxiAoAmoXChMI4J2n-Z2PiwMVAAAAAB0AAAAAEA8..i&imgrefurl=https%3A%2F%2Fwww.rentvillasalgarve.co.uk%2F&docid=TF4EoHH-oNiY2M&w=600&h=420&itg=1&q=villas&ved=0CBIQxiAoAmoXChMI4J2n-Z2PiwMVAAAAAB0AAAAAEA8",
                            Name = "Paradise Villa",
                            Occupancy = 4,
                            Price = 600.0,
                            Sqft = 100,
                            UpdatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1773)
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 0,
                            CreatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1783),
                            Description = "This is details of Villa 4",
                            ImageUrl = "https://www.google.com/imgres?imgurl=https%3A%2F%2Fvillaimages.villaplus.com%2Fimages%2Fvillas%2Fphotos%2F8bb14538-2835-41ba-9c8c-e739fd8069a5_725.jpg&tbnid=H7579zpt_96g-M&vet=10CBYQxiAoCGoXChMI4J2n-Z2PiwMVAAAAAB0AAAAAEA8..i&imgrefurl=https%3A%2F%2Fwww.villaplus.com%2Fdestinations%2Fvillas-in-spain%2Fvillas-in-balearic-islands%2Fmenorca%2Fcalan-porter&docid=t6qGL44sGUmn4M&w=725&h=482&itg=1&q=villas&ved=0CBYQxiAoCGoXChMI4J2n-Z2PiwMVAAAAAB0AAAAAEA8",
                            Name = "Luxury Villa",
                            Occupancy = 4,
                            Price = 700.0,
                            Sqft = 120,
                            UpdatedDate = new DateTime(2025, 2, 3, 19, 33, 22, 679, DateTimeKind.Local).AddTicks(1780)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
